# spring configuration
spring:
   application:
      name: myweb
      
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
         
# server configuration
server:
   port: 8088
   servlet:
      context-path: /
      encoding:
         carset: utf-8
         enabled: true